import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    appName: 'Bakery ERP',
    dashboard: 'Dashboard',
    manageShops: 'Manage Shops',
    warehouse: 'Warehouse',
    production: 'Production',
    shopRequests: 'Shop Requests',
    analytics: 'Analytics',
    distribution: 'Distribution',
    myShops: 'My Shops',
    switchRole: 'Switch Role',
    logout: 'Logout',
    welcome: 'Welcome to Bakery ERP',
    selectRole: 'Select your role to access your dashboard.',
    shopOwner: 'Shop Owner',
    admin: 'Admin / Warehouse',
    addShop: 'Add New Shop',
    currentShops: 'Current Shops',
    name: 'Name',
    location: 'Location',
    contact: 'Contact',
    action: 'Action',
    delete: 'Delete',
    add: 'Add',
    cancel: 'Cancel',
    login: 'Login',
    enterPassword: 'Enter Admin Password',
    incorrectPassword: 'Incorrect password',
    sell: 'Sell',
    requestStock: 'Request Stock',
    selectProduct: 'Select Product',
    quantity: 'Quantity',
    noStock: 'No stock available',
    noSales: 'No sales yet',
    produced: 'Produced',
    warehouseStock: 'Warehouse Stock',
    sentToShops: 'Sent to Shops',
    delivered: 'Delivered',
    sold: 'Sold',
    shopStock: 'Shop Stock',
    totalProduced: 'Total Produced',
    totalSales: 'Total Sales',
    dailySales: 'Daily Sales',
    rawMaterialUsage: 'Raw Material Usage',
    pendingRequests: 'Pending Requests',
    fulfill: 'Deliver & Fulfill',
    noPending: 'No pending requests.',
    addMaterial: 'Add Material',
    submitBatch: 'Submit Batch',
    productionOutput: 'Production Output',
    recentBatches: 'Recent Batches',
    productName: 'Product Name',
    quantityProduced: 'Quantity Produced',
    consumptions: 'Consumptions',
    purchase: 'Purchase',
    addToWarehouse: 'Add to Warehouse',
    materialName: 'Material Name',
    unit: 'Unit',
    stock: 'Stock',
    shopPerformance: 'Shop Performance',
    salesByProduct: 'Sales by Product',
    salesTrend: 'Sales Trend',
    fullDeliveryHistory: 'Full Delivery History',
    noDeliveries: 'No deliveries recorded.',
    date: 'Date',
    qtyDelivered: 'Quantity Delivered',
    productCatalog: 'Product Catalog',
    requestingForShop: 'Requesting for Shop',
    catalogHint: 'Find new products and place orders directly to the warehouse.',
    available: 'Available',
    sending: 'Sending...',
    requested: 'Requested',
    items: 'Items',
    salesChart: 'Sales Breakdown',
    selectMaterial: 'Select Material',
    addProduction: 'Add Production',
    success: 'successfully',
    product: 'Product',
    comparisonChart: 'Delivered vs Sold',
    productOverview: 'Product Overview',
    productStatus: 'Product Status',
    products: 'Products',
    totalDelivered: 'Total Delivered',
    totalSold: 'Total Sold',
    productionVsDistribution: 'Production vs Distribution',
  },
  hi: {
    appName: 'बेकरी ईआरपी',
    dashboard: 'डैशबोर्ड',
    manageShops: 'दुकानें प्रबंधित करें',
    warehouse: 'गोदाम',
    production: 'उत्पादन',
    shopRequests: 'दुकान अनुरोध',
    analytics: 'विश्लेषण',
    distribution: 'वितरण',
    myShops: 'मेरी दुकानें',
    switchRole: 'भूमिका बदलें',
    logout: 'लॉगआउट',
    welcome: 'बेकरी ईआरपी में आपका स्वागत है',
    selectRole: 'अपनी भूमिका का चयन करें।',
    shopOwner: 'दुकान मालिक',
    admin: 'प्रशासक / गोदाम',
    addShop: 'नई दुकान जोड़ें',
    currentShops: 'वर्तमान दुकानें',
    name: 'नाम',
    location: 'स्थान',
    contact: 'संपर्क',
    action: 'कार्य',
    delete: 'हटाएं',
    add: 'जोड़ें',
    cancel: 'रद्द करें',
    login: 'लॉगिन',
    enterPassword: 'प्रशासक पासवर्ड दर्ज करें',
    incorrectPassword: 'गलत पासवर्ड',
    sell: 'बेचें',
    requestStock: 'स्टॉक मांगें',
    selectProduct: 'उत्पाद चुनें',
    quantity: 'मात्रा',
    noStock: 'कोई स्टॉक उपलब्ध नहीं',
    noSales: 'अभी तक कोई बिक्री नहीं',
    produced: 'उत्पादित',
    warehouseStock: 'गोदाम स्टॉक',
    sentToShops: 'दुकानों को भेजा गया',
    delivered: 'वितरित',
    sold: 'बेचा गया',
    shopStock: 'दुकान स्टॉक',
    totalProduced: 'कुल उत्पादित',
    totalSales: 'कुल बिक्री',
    dailySales: 'दैनिक बिक्री',
    rawMaterialUsage: 'कच्चे माल का उपयोग',
    pendingRequests: 'लंबित अनुरोध',
    fulfill: 'वितरित करें और पूरा करें',
    noPending: 'कोई लंबित अनुरोध नहीं।',
    addMaterial: 'सामग्री जोड़ें',
    submitBatch: 'बैच सबमिट करें',
    productionOutput: 'उत्पादन आउटपुट',
    recentBatches: 'हाल के बैच',
    productName: 'उत्पाद का नाम',
    quantityProduced: 'उत्पादित मात्रा',
    consumptions: 'उपभोग',
    purchase: 'खरीद',
    addToWarehouse: 'गोदाम में जोड़ें',
    materialName: 'सामग्री का नाम',
    unit: 'इकाई',
    stock: 'स्टॉक',
    shopPerformance: 'दुकान प्रदर्शन',
    salesByProduct: 'उत्पाद द्वारा बिक्री',
    salesTrend: 'बिक्री प्रवृत्ति',
    fullDeliveryHistory: 'पूर्ण वितरण इतिहास',
    noDeliveries: 'कोई वितरण दर्ज नहीं।',
    date: 'तारीख',
    qtyDelivered: 'वितरित मात्रा',
    productCatalog: 'उत्पाद सूची',
    requestingForShop: 'दुकान के लिए अनुरोध',
    catalogHint: 'नए उत्पाद खोजें और गोदाम को सीधे ऑर्डर भेजें।',
    available: 'उपलब्ध',
    sending: 'भेजा जा रहा है...',
    requested: 'अनुरोधित',
    items: 'आइटम',
    salesChart: 'बिक्री विवरण',
    selectMaterial: 'सामग्री चुनें',
    addProduction: 'उत्पादन जोड़ें',
    success: 'सफलतापूर्वक',
    product: 'उत्पाद',
    comparisonChart: 'वितरित बनाम बेचा गया',
    productOverview: 'उत्पाद अवलोकन',
    productStatus: 'उत्पाद स्थिति',
    products: 'उत्पाद',
    totalDelivered: 'कुल वितरित',
    totalSold: 'कुल बेचा गया',
    productionVsDistribution: 'उत्पादन बनाम वितरण',
  },
  mr: {
    appName: 'बेकरी ईआरपी',
    dashboard: 'डॅशबोर्ड',
    manageShops: 'दुकाने व्यवस्थापित करा',
    warehouse: 'गोदाम',
    production: 'उत्पादन',
    shopRequests: 'दुकान विनंती',
    analytics: 'विश्लेषण',
    distribution: 'वितरण',
    myShops: 'माझी दुकाने',
    switchRole: 'भूमिका बदला',
    logout: 'बाहेर पडा',
    welcome: 'बेकरी ईआरपी मध्ये स्वागत आहे',
    selectRole: 'आपली भूमिका निवडा.',
    shopOwner: 'दुकान मालक',
    admin: 'प्रशासक / गोदाम',
    addShop: 'नवीन दुकान जोडा',
    currentShops: 'सध्या असलेली दुकाने',
    name: 'नाव',
    location: 'स्थान',
    contact: 'संपर्क',
    action: 'क्रिया',
    delete: 'हटवा',
    add: 'जोडा',
    cancel: 'रद्द करा',
    login: 'लॉगिन',
    enterPassword: 'प्रशासक पासवर्ड प्रविष्ट करा',
    incorrectPassword: 'चुकीचा पासवर्ड',
    sell: 'विक्री करा',
    requestStock: 'स्टॉकची विनंती करा',
    selectProduct: 'उत्पादन निवडा',
    quantity: 'प्रमाण',
    noStock: 'स्टॉक उपलब्ध नाही',
    noSales: 'अद्याप विक्री झालेली नाही',
    produced: 'उत्पादित',
    warehouseStock: 'गोदाम स्टॉक',
    sentToShops: 'दुकानांना पाठवले',
    delivered: 'वितरित',
    sold: 'विकले',
    shopStock: 'दुकान स्टॉक',
    totalProduced: 'एकूण उत्पादित',
    totalSales: 'एकूण विक्री',
    dailySales: 'दैनंदिन विक्री',
    rawMaterialUsage: 'कच्चा माल वापर',
    pendingRequests: 'प्रलंबित विनंत्या',
    fulfill: 'वितरित करा आणि पूर्ण करा',
    noPending: 'कोणत्याही प्रलंबित विनंती नाही.',
    addMaterial: 'साहित्य जोडा',
    submitBatch: 'बॅच सबमिट करा',
    productionOutput: 'उत्पादन आउटपुट',
    recentBatches: 'अलीकडील बॅचेस',
    productName: 'उत्पादनाचे नाव',
    quantityProduced: 'उत्पादित प्रमाण',
    consumptions: 'वापर',
    purchase: 'खरेदी',
    addToWarehouse: 'गोदामात जोडा',
    materialName: 'साहित्याचे नाव',
    unit: 'एकक',
    stock: 'स्टॉक',
    shopPerformance: 'दुकान कामगिरी',
    salesByProduct: 'उत्पादनानुसार विक्री',
    salesTrend: 'विक्री ट्रेंड',
    fullDeliveryHistory: 'संपूर्ण वितरण इतिहास',
    noDeliveries: 'कोणतीही वितरण नोंदणी नाही.',
    date: 'तारीख',
    qtyDelivered: 'वितरित प्रमाण',
    productCatalog: 'उत्पादन यादी',
    requestingForShop: 'दुकानासाठी विनंती',
    catalogHint: 'नवीन उत्पादने शोधा आणि थेट गोदामात ऑर्डर पाठवा.',
    available: 'उपलब्ध',
    sending: 'पाठवत आहे',
    requested: 'विनंती केलेली',
    items: 'वस्तू',
    salesChart: 'विक्री तपशील',
    selectMaterial: 'साहित्य निवडा',
    addProduction: 'उत्पादन जोडा',
    success: 'यशस्वीरित्या',
    product: 'उत्पादन',
    comparisonChart: 'वितरित वि. विकले',
    productOverview: 'उत्पादन विहंगावलोकन',
    productStatus: 'उत्पादन स्थिती',
    products: 'उत्पादने',
    totalDelivered: 'एकूण वितरित',
    totalSold: 'एकूण विकले',
    productionVsDistribution: 'उत्पादन वि. वितरण',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);